name: ClickUp Reminder Bot

on:
  schedule:
    - cron: '0 9 * * 1-5'  # Weekdays 9 AM UTC (Monday-Friday)
  workflow_dispatch:  # Manual trigger for testing

jobs:
  run-bot:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run ClickUp Reminder Bot
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}
          CLICKUP_API_KEY: ${{ secrets.CLICKUP_API_KEY }}
          CLICKUP_TEAM_ID: ${{ secrets.CLICKUP_TEAM_ID }}
        run: |
          echo "🚀 Starting ClickUp Reminder Bot..."
          python main.py
          echo "✅ Bot execution completed!" 